class UserState:
    IDLE = "IDLE"
    WAITING_FOR_EMAIL = "WAITING_FOR_EMAIL"
    CONFIRMING_EMAIL_CHANGE = "CONFIRMING_EMAIL_CHANGE"
    WAITING_FOR_REQUEST_BUTTON = "WAITING_FOR_REQUEST_BUTTON"
    WAITING_FOR_TOPIC = "WAITING_FOR_TOPIC"
    WAITING_FOR_MESSAGE_TEXT = "WAITING_FOR_MESSAGE_TEXT"
